# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: hive-metastore
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: hive-metastore
#   template:
#     metadata:
#       labels:
#         app: hive-metastore
#     spec:
#       containers:
#       - name: metastore
#         image: apache/hive:3.1.3
#         ports:
#           - containerPort: 9083
#         env:
#           - name: SERVICE_NAME
#             value: metastore
