# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: minio
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: minio
#   template:
#     metadata:
#       labels:
#         app: minio
#     spec:
#       containers:
#       - name: minio
#         image: minio/minio
#         args:
#           - server
#           - /data
#         env:
#           - name: MINIO_ROOT_USER
#             value: admin
#           - name: MINIO_ROOT_PASSWORD
#             value: password
#         ports:
#           - containerPort: 9000
