apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Gunte\scoop\apps\kompose\current\kompose.exe convert --chart
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: airflow
  name: airflow
spec:
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8080
  selector:
    io.kompose.service: airflow
