apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Gunte\scoop\apps\kompose\current\kompose.exe convert --chart
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: hive-metastore
  name: hive-metastore
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hive-metastore
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Gunte\scoop\apps\kompose\current\kompose.exe convert --chart
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: hive-metastore
    spec:
      containers:
        - env:
            - name: DB_DRIVER
              value: postgres
            - name: HIVE_METASTORE_DB_TYPE
              value: postgres
            - name: SERVICE_NAME
              value: metastore
          image: apache/hive:3.1.3
          name: hive-metastore
          ports:
            - containerPort: 9083
              protocol: TCP
          volumeMounts:
            - mountPath: /opt/hive/conf
              name: hive-metastore-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: hive-metastore-cm0
          name: hive-metastore-cm0
