apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Gunte\scoop\apps\kompose\current\kompose.exe convert --chart
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: hive-metastore
  name: hive-metastore
spec:
  ports:
    - name: "9083"
      port: 9083
      targetPort: 9083
  selector:
    io.kompose.service: hive-metastore
