apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Gunte\scoop\apps\kompose\current\kompose.exe convert --chart
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: metastore-db
  name: metastore-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: metastore-db
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Gunte\scoop\apps\kompose\current\kompose.exe convert --chart
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: metastore-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: metastore
            - name: POSTGRES_PASSWORD
              value: hive
            - name: POSTGRES_USER
              value: hive
          image: postgres:13
          livenessProbe:
            exec:
              command:
                - pg_isready -U hive -d metastore
            failureThreshold: 3
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 10
          name: metastore-db
      restartPolicy: Always
