apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Gunte\scoop\apps\kompose\current\kompose.exe convert --chart
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: minio-init
  name: minio-init
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio-init
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Gunte\scoop\apps\kompose\current\kompose.exe convert --chart
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: minio-init
    spec:
      containers:
        - command:
            - /bin/sh
            - -c
            - ' sleep 5 && mc alias set local http://minio:9000 admin password && mc mb -p local/warehouse '
          env:
            - name: MINIO_ROOT_PASSWORD
              value: password
            - name: MINIO_ROOT_USER
              value: admin
          image: minio/mc
          name: minio-init
      restartPolicy: Always
