apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\Gunte\scoop\apps\kompose\current\kompose.exe convert --chart
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: minio
  name: minio
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "9001"
      port: 9001
      targetPort: 9001
  selector:
    io.kompose.service: minio
