apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Gunte\scoop\apps\kompose\current\kompose.exe convert --chart
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: spark
  name: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Gunte\scoop\apps\kompose\current\kompose.exe convert --chart
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: spark
    spec:
      containers:
        - image: spark
          livenessProbe:
            exec:
              command:
                - echo ok
            failureThreshold: 3
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 10
          name: spark
          volumeMounts:
            - mountPath: /etl
              name: spark-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: spark-cm0
          name: spark-cm0
