apiVersion: v1
data:
  config.properties: |-
    coordinator=true
    node-scheduler.include-coordinator=false
    http-server.http.port=8080
    # discovery.uri=http://example.net:8080

    # show experimental webui
    web-ui.preview.enabled=true
  generator.properties: |-
    connector.name=faker
    faker.null-probability=0.1
    faker.default-limit=1000
    faker.locale=pl
  hive.properties: |-
    connector.name=hive
    hive.metastore.uri=thrift://hive-metastore:9083

    # hive.s3.endpoint=http://minio:9000
    # hive.s3.aws-access-key=${MINIO_USER}
    # hive.s3.aws-secret-key=${MINIO_PASSWORD}
  iceberg.properties: |-
    connector.name=iceberg

    # Iceberg catalog backed by Hive Metastore
    iceberg.catalog.type = hive_metastore
    iceberg.file-format = PARQUET
    iceberg.compression-codec = ZSTD

    hive.metastore.uri=thrift://hive-metastore:9083

    # MinIO / S3 config (Trino-style)
    fs.hadoop.enabled=false
    fs.native-s3.enabled=true

    s3.endpoint=http://minio:9000
    s3.aws-access-key=${MINIO_USER}
    s3.aws-secret-key=${MINIO_PASSWORD}
    s3.path-style-access=true
    s3.region=us-east-1
  tpcds.properties: |-
    connector.name=tpcds
    tpcds.splits-per-node=4
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: trino
  name: trino-cm0
