apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\Gunte\scoop\apps\kompose\current\kompose.exe convert --chart
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: trino
  name: trino
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: trino
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\Gunte\scoop\apps\kompose\current\kompose.exe convert --chart
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: trino
    spec:
      containers:
        - image: trinodb/trino:latest
          livenessProbe:
            exec:
              command:
                - curl
                - -f
                - http://localhost:8080/v1/info
            failureThreshold: 3
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 10
          name: trino
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /etc/trino/catalog
              name: trino-cm0
      restartPolicy: Always
      volumes:
        - configMap:
            name: trino-cm0
          name: trino-cm0
